### PR TITLE
Add flag for specifying number of spaces

### PR DESCRIPTION
**Pull request by fsmiamoto**
I wanted to have some extra spacing so having a flag for that might come in handy.

Let me know what you think.

### CODE REVIEW

**Comment by xyproto** [comment]
Thanks for the PR. I like the idea of being able to specify the number of spaces, but I believe the flag handling crosses the threshold for where the flag package becomes useful.

If just `-i` is supplied, without a filename, will it crash?

**Comment by xyproto** [comment]
I double checked. `fstabfmt -i` makes `fstabfmt` panic instead of printing the usage information:

```
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main()
	/home/afr/clones/fstabfmt-fsmiamoto/main.go:106 +0x70f
```

**Comment by fsmiamoto** [comment]
>  but I believe the flag handling crosses the threshold for where the flag package becomes useful.

Totally agreed, I wanted to have a first rough version to present the idea - which left some bugs like you pointed out - but using the flag package would help here.

I'll work on the refactor then :)

**Comment by xyproto** [comment]
Looking forward to it. :slightly_smiling_face:

**Comment by fsmiamoto** [comment]
I've made the changes to use the flag package and also updated the README.
Let me know what you think :slightly_smiling_face:

**Comment by xyproto** [comment]
Thanks! Merged.

**Pull request merged**
